<a href="https://colab.research.google.com/github/sadicsha/Numpy-in-python/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy

In [ ]:
import numpy as np

creating a list 
creating array with help of this list 

In [ ]:
lst_np=[1,2,3,4,5,6,7,8,9,10]
print(lst_np)
print(type(lst_np))
arr1 = np.array(lst_np)
print(arr1)
print(type(arr1))
arr1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
<class 'list'>
[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr2=np.array([1,2,3,4,5,6,7,8,9,10])
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

how to identify if it if 1D array or 2D array or 3D array

1D=[1,2,3,4,5,6,7,8,9,]

2D=[[1,2,3,4,5],[6,7,8,9,10]]

3D=collection of multiple 2D array
[[[1,2,3,4,5],[6,7,8,9,10]],
[[1,2,3,4,5],[6,7,8,9,10]],
[[1,2,3,4,5],[6,7,8,9,10]]]

In [ ]:
array_1d=np.array([1,2,3,4,5,6,7,8,9,])
print(array_1d)
print(type(array_1d))

array_2d=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(array_2d)
print(type(array_2d))

array_3d=np.array([[[1,2,3,4,5],[6,7,8,9,10]],
                    [[1,2,3,4,5],[6,7,8,9,10]],
                    [[1,2,3,4,5],[6,7,8,9,10]]])
print(array_3d)
print(type(array_3d))

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
<class 'numpy.ndarray'>
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9 10]]]
<class 'numpy.ndarray'>
