<a href="https://colab.research.google.com/github/sadicsha/Numpy-in-python/blob/main/numpy_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# importing package
import numpy
  
# create numpy array
arr = numpy.array([[1, 2, 3, 4, 5],
                   [6, 7, 8, 9, 10],
                   [11, 12, 13, 14, 15],
                   [16, 17, 18, 19, 20]
                   ])
  
# view array
print(arr)
  
# check for some lists
print([1, 2, 3, 4, 5] in arr.tolist())
print([16, 17, 20, 19, 18] in arr.tolist())
print([3, 2, 5, -4, 5] in arr.tolist())
print([11, 12, 13, 14, 15] in arr.tolist())

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
True
False
False
True


In [2]:
# Importing Numpy module
import numpy as np
  
# Creating 5X4 2-D Numpy array
n_arr = np.array([[10.5, 22.5, 3.8, 5],
                  [23.45, 50, 78.7, 3.5],
                  [41, np.nan, np.nan, 0],
                  [20, 50.20, np.nan, 2.5],
                  [18.8, 50.60, 8.8, 58.6]])
  
print("Given array:")
print(n_arr)
  
print("\nRemove all rows containing non-numeric elements")
print(n_arr[~np.isnan(n_arr).any(axis=1)])

Given array:
[[10.5  22.5   3.8   5.  ]
 [23.45 50.   78.7   3.5 ]
 [41.     nan   nan  0.  ]
 [20.   50.2    nan  2.5 ]
 [18.8  50.6   8.8  58.6 ]]

Remove all rows containing non-numeric elements
[[10.5  22.5   3.8   5.  ]
 [23.45 50.   78.7   3.5 ]
 [18.8  50.6   8.8  58.6 ]]


In [3]:
# Python Program to create array with all ones
import numpy as geek

a = geek.ones(3, dtype = int)
print("Matrix a : \n", a)

b = geek.ones([3, 3], dtype = int)
print("\nMatrix b : \n", b)


Matrix a : 
 [1 1 1]

Matrix b : 
 [[1 1 1]
 [1 1 1]
 [1 1 1]]


In [5]:
# Python program explaining
# numpy.squeeze function
import numpy as geek
in_arr = geek.arange(9).reshape(1, 3, 3)

print ("Input array : ", in_arr)
out_arr = geek.squeeze(in_arr, axis = 0)

print ("output array : ", out_arr)
print("The shapes of Input and Output array : ")

print(in_arr.shape, out_arr.shape)


Input array :  [[[0 1 2]
  [3 4 5]
  [6 7 8]]]
output array :  [[0 1 2]
 [3 4 5]
 [6 7 8]]
The shapes of Input and Output array : 
(1, 3, 3) (3, 3)
